### PR TITLE
US16 // categories - edit and delete

### PR DESCRIPTION
**Pull request by matschi3**
on `categories`/`Kategorien` page you can edit and delete categories.
Click a button and get yourself a cup of tea, cause the database takes its time ✌🏼

[US16](https://github.com/matschi3/capstone/issues/27)
[Deployment](https://capstone-iz141ycu6-matschi3.vercel.app/categories)

### CODE REVIEW

**Review by doemser — CHANGES_REQUESTED** [review]
Your preview deployment fails, and there is an error thrown in the console.
Screenshot 2023-07-11 at 14 50 27

**Comment by matschi3** [comment]
// reset database

**Review by TmWgnr — APPROVED** [review]
Code looks fine.  nevertheless their seems to be a problem with your GET request in the console when opening items and teile..kategorien seems to be fine..
maybe you can check console in your terminal what happens when pushing to the mentioned pages

**Comment by matschi3** [comment]
// fixed error

**Pull request merged**
